version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: ./infra/php/Dockerfile
        volumes:
            - ./backend:/var/www/html
    web:
        build:
            context: .
            dockerfile: ./infra/nginx/Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./backend:/var/www/html